#!/bin/sh 
#load global env 

. ../../cfg/cpe_env_global
. ../../cfg/ppa_auto_env
. ../../cfg/ppa_auto_testcase_env

#load local env
. cpe/cpe_env
. wan/wan_env
. lan/lan_env

#echo $cpe_lan_ip
set_ip_address "$ppa_auto_if_cpe" "$lan_ip"
set_routeing_table_lanside "$cpe_wan_subnet" "$cpe_lan_ip" "$cpe_wan_netmask"

killall iperf
iperf -s -p 5002 & 
