#!/bin/sh
#load global env

. ../../cfg/cpe_env_global
. ../../cfg/ppa_auto_env
. ../../cfg/ppa_auto_testcase_env

#load local env
. cpe/cpe_env
. wan/wan_env
. lan/lan_env

sec=20

iperf -c "$tmp_cpe_lan_ip" -i 1 -t 10 -p 5002 -P 8 >  $ppa_auto_testcase_log_folder/result
cat $ppa_auto_testcase_log_folder/result | grep sec | head -$sec | tail -1 | tr - " " | awk '{print $4,$8,$9}' > $ppa_auto_packet_result_file

