#!/bin/sh
. /var/cpe_env_global
#bridge with single wan itnerface and single outvlan. LAN no vlan
#br0: $cpe_lan_if $phy_wan_ifname0
. /var/ppa_auto_env
. /var/cpe_env



#start_firewall_enable

#clear all mibs
echo clear > /proc/mpe/tc_mib

