#!/bin/sh

pvc=$pvc_llc_br_vlan1;  export pvc
nas_index=$(get_nas_index $pvc); export nas_index
phy_wan_ifname0=$(rework_wan_ifname "$phy_wan_ifname0" "$nas_index");
ppa_echo phy_wan_ifname0=$phy_wan_ifname0

#define lan/wan interfaces:
cpe_lan_base_if=$phy_lan_ifname0;    		 export cpe_lan_base_if
lan_vlan_id=$lan_vlan1                           export lan_vlan_id
cpe_lan_if="$cpe_lan_base_if.$lan_vlan_id";      export cpe_lan_if
cpe_wan_base_if=$phy_wan_ifname0;                export cpe_wan_base_if

wan_vlan_id=$wan_llc_br_vlan1_id;                export wan_vlan_id
cpe_wan_if="$cpe_wan_base_if.$wan_vlan_id";      export cpe_wan_if
cpe_nat_enable=1;                                export cpe_nat_enable
cpe_wan_vlan_s=1;                                export cpe_wan_vlan_s
cpe_wan_vlan_e=6;                                export cpe_wan_vlan_e
#--------------------------------Define CPE LAN/WAN IP and LAN PC IP--------------------------------Begin

#define cpe lan subnet    *************** Need change it according to different test case
cpe_lan_subnet=$lan_subnet_vlan1
export cpe_lan_subnet

#define cpe lan netmask
cpe_lan_netmask=$lan_subnet_vlan1_mask
export cpe_lan_netmask

#--------------------------------Define CPE WAN IP--------------------------------Begin
#define cpe wan subnet  ************** Need change it according to different test case
cpe_wan_subnet=$wan_subnet_llc_br_vlan1
export cpe_wan_subnet

cpe_wan_netmask=$wan_subnet_llc_br_vlan1_mask
export cpe_wan_netmask

#define multicast_ip   ************** Need change it according to different test case
multicast_ip=$wan_subnet_llc_br_vlan1_mc
export multicast_ip

#define multicast_ip  number ************** Need change it according to different test case
multicast_ip_num=$wan_subnet_llc_br_vlan1_mc_num
export multicast_ip_num


#create cpe lan interface ip according to its subnet and ppa automation session name
get_cpe_lan_ip $lan_subnet_basic_ipv6_vlan2_part_address
cpe_lan_ip=$tmp_cpe_lan_ip
export cpe_lan_ip

#create lan pc ip according to its subnet and ppa automation session name
get_lan_ip_route_mode $lan_subnet_basic_ipv6_vlan2_part_address
lan_ip=$tmp_lan_ip_route_mode
export lan_ip


#create 2 [one for tunnelling device and another for CPE wan interface ]cpe wan interface ip according to its subnet and ppa automation session name for 6rd tunnelling
get_cpe_wan_ip $wan_subnet_6rd_ipv6_vlan2_part_address
cpe_wan_ip_6rd_ipv6=$tmp_cpe_wan_ip
export cpe_wan_ip_6rd_ipv6

get_cpe_wan_ip $cpe_wan_subnet
cpe_wan_ip_ipv4=$tmp_cpe_wan_ip
export cpe_wan_ip_ipv4


#create 2 cpe wan interface for 6rd. Always set first ip for gw according to its subnet
get_cpe_gw_ip $wan_subnet_6rd_ipv6_vlan2_part_address
cpe_wan_gw_6rd_ipv6=$tmp_cpe_gw_ip
export cpe_wan_gw_6rd_ipv6

get_cpe_gw_ip $cpe_wan_subnet
cpe_wan_gw_ipv4=$tmp_cpe_gw_ip
export cpe_wan_gw_ipv4 



if [ $enable_ips_debug -eq 1 ]; then
    echo "cpe_lan_subnet=$cpe_lan_subnet"
    echo "cpe_lan_netmask=$cpe_lan_netmask"
    echo "cpe_lan_ip=$cpe_lan_ip"
    echo "lan_ip=$lan_ip"

    echo "cpe_wan_subnet=$cpe_wan_subnet"
    echo "cpe_wan_ip=$cpe_wan_ip"
    echo "cpe_wan_gw=$cpe_wan_gw"

    echo "multicast_ip=$multicast_ip"
    echo "cpe_wan_base_if=$cpe_wan_base_if"
    echo "cpe_wan_if=$cpe_wan_if"
    echo "wan_vlan_id=$wan_vlan_id"
fi

