#!/bin/sh 
#load global env 

. ../../cfg/cpe_env_global
. ../../cfg/ppa_auto_env
. ../../cfg/ppa_auto_testcase_env

#load local env
. cpe/cpe_env
. wan/wan_env
. lan/lan_env


set_routeing_table_wanside "$lan_ip" "$cpe_wan_ip" "128" "$fixed_wan_side_if.$wan_vlan_id"

set_ipv6_mac_neigh_table_wanside "$fixed_wan_side_if.$wan_vlan_id" "$cpe_wan_ip" 

get_ipv6_mac_address_wan "$fixed_wan_side_if"

