#!/bin/sh 

. ../../cfg/cpe_env_global
#load global env 
. ../../cfg/ppa_auto_env
. ../../cfg/ppa_auto_testcase_env

#load local env
. cpe/cpe_env
. lan/lan_env
. wan/wan_env

#upload cpe_pre_verify and run it
download_file "cpe/cpe_pre_verify" "/var/t.sh"
#$ppa_auto_tool -i $ppa_auto_if_cpe -n $ppa_auto_name -t cpe -c put -s cpe/cpe_pre_verify -d /var/t.sh  -g $ppa_auto_debug
#ppa_sleep  1

$ppa_auto_tool -i $ppa_auto_if_cpe -n $ppa_auto_name -t cpe -c run -s /var/t.sh                        -g $ppa_auto_debug
#ppa_sleep  1

get_wanserver_if_via_cpe_wanif $cpe_wan_if $fixed_wan_side_if
cmd="$wan_ppa_bin_path/mc_trigger.sh $wan_ppa_bin_path $ppa_auto_name $tmp_wanserver_if $multicast_ip $multicast_ip_num &"
${ppa_auto_tool_path} -i $ppa_auto_if_wan -n $ppa_auto_name -t wan -c cmd -s "$cmd"



