#!/bin/sh

. ../../cfg/cpe_env_global
#load global env
. ../../cfg/ppa_auto_env
. ../../cfg/ppa_auto_testcase_env

#load local env
. cpe/cpe_env
. lan/lan_env
. wan/wan_env

if [ -f $ppa_auto_packet_id_file ]; then
   . $ppa_auto_packet_id_file
   kill -s 10  $packet_id
   #ppa_sleep  3
fi

download_file "cpe/cpe_stop_verify" "/var/t.sh"
#upload and run command: cpe_stop_verify
#$ppa_auto_tool -i $ppa_auto_if_cpe -n $ppa_auto_name -t cpe -c put -s cpe/cpe_stop_verify -d /var/t.sh  -g $ppa_auto_debug
#ppa_sleep  2

$ppa_auto_tool -i $ppa_auto_if_cpe -n $ppa_auto_name -t cpe -c run -s /var/t.sh                    -g $ppa_auto_debug
