#!/bin/sh 

. /var/cpe_env_global
#NAT mode with single wan interface and lan interface, both without any vlan
#br0: $cpe_lan_if
#br0 <--> NAT <--> nas0.3
#
. /var/ppa_auto_env
. /var/cpe_env

#init dsl_atm if necessary
start_dsl_atm

start_firewall_flush

#ppa_sleep  5
#$1: routed(0)/bridge(1) 
#$2: nas index
#$3: encapsulation: LLC(0)/LLC(1)
#$4: 
start_br2684 1 $nas_index1 0 "UBR,aal5:" "0.$pvc1"
start_br2684 1 $nas_index2 0 "UBR,aal5:" "0.$pvc2"
brctl addbr br1
set_br_mac_up br0 1
set_br_mac_up br1 2

set_ip_address "br0" $cpe_lan_ip1
set_ip_address "br1" $cpe_lan_ip2
set_ip_address "$cpe_lan_if1" "0.0.0.0"
set_ip_address "$cpe_lan_if2" "0.0.0.0"
brctl addif br0 $cpe_lan_if1
brctl addif br1 $cpe_lan_if2
brctl delif br0 $cpe_lan_base_if
ifconfig $cpe_lan_if1 0.0.0.0 up
ifconfig $cpe_lan_if2 0.0.0.0 up
ifconfig $cpe_wan_base_if0 0.0.0.0 up
ifconfig $cpe_wan_base_if1 0.0.0.0 up


