#!/bin/sh

. ../../cfg/cpe_env_global
#load global env 
. ../../cfg/ppa_auto_env
. ../../cfg/ppa_auto_testcase_env

#load local env
. cpe/cpe_env
. lan/lan_env
. wan/wan_env

../../bin/Wan_Reset_Script.sh


wan/wan_init

