#!/bin/sh 
#load global env 

. ../../cfg/cpe_env_global
. ../../cfg/ppa_auto_env
. ../../cfg/ppa_auto_testcase_env

#load local env
. cpe/cpe_env
. wan/wan_env
. lan/lan_env

set_ip_address "$ppa_auto_if_cpe" "$lan_ip"
ip route add $cpe_wan_gw_gre dev $ppa_auto_if_cpe


