#!/bin/sh 

. /var/cpe_env_global
#bridge with single wan itnerface and single outvlan. LAN no vlan
#br0: $cpe_lan_if 
. /var/ppa_auto_env
. /var/cpe_env


if [ $cpe_nat_enable -gt 0 ]; then 
    iptables -t nat -A POSTROUTING -o $cpe_wan_if -j MASQUERADE
fi

echo 1 > /proc/sys/net/ipv4/ip_forward
echo 1 > /proc/sys/net/ipv6/conf/all/forwarding
echo 1 > /proc/sys/net/netfilter/nf_conntrack_tcp_be_liberal  


echo "ip tunnel add $Tunnel_Dev_6rd_Name mode sit local $cpe_wan_ip_ipv4 remote $cpe_wan_gw_ipv4 ttl 64"
ip tunnel add $Tunnel_Dev_6rd_Name mode sit local $cpe_wan_ip_ipv4 remote $cpe_wan_gw_ipv4 ttl 64

#ppa_sleep 1

echo "ifconfig $Tunnel_Dev_6rd_Name up"
ifconfig $Tunnel_Dev_6rd_Name up

#ppa_sleep 1

echo "set_ipv6_address "$Tunnel_Dev_6rd_Name" "$cpe_wan_ip_6rd_ipv6" "$ipv6_subnetmask""
set_ip_address "$Tunnel_Dev_6rd_Name" "$cpe_wan_ip_6rd_ipv6" "$ipv6_subnetmask"

#ppa_sleep 1

echo "set_ipv4_address "$cpe_wan_if" "$cpe_wan_ip_ipv4""
set_ip_address "$cpe_wan_if" "$cpe_wan_ip_ipv4"


