#!/bin/sh

. ../../cfg/cpe_env_global
#load global env 
. ../../cfg/ppa_auto_env
. ../../cfg/ppa_auto_testcase_env

#load local env
. cpe/cpe_env
. lan/lan_env
. wan/wan_env

../../bin/Cpe_Reset_Script.sh

#upload cpe_env which will be used by later script
#$ppa_auto_tool -i $ppa_auto_if_cpe -n $ppa_auto_name -t cpe -c put -s ../../cfg/ppa_auto_env   -d /var/ -g $ppa_auto_debug
$ppa_auto_tool -i $ppa_auto_if_cpe -n $ppa_auto_name -t cpe -c put -s ../../cfg_current/cpe_env_global -d /var/ -g $ppa_auto_debug
$ppa_auto_tool -i $ppa_auto_if_cpe -n $ppa_auto_name -t cpe -c put -s cpe/cpe_env           -d /var/ -g $ppa_auto_debug

#upload script & run it
#ppa_sleep  2
$ppa_auto_tool -i $ppa_auto_if_cpe -n $ppa_auto_name -t cpe -c put -s cpe/cpe_init -d /var/t.sh  -g $ppa_auto_debug

#ppa_sleep  1
$ppa_auto_tool -i $ppa_auto_if_cpe -n $ppa_auto_name -t cpe -c run -s /var/t.sh                  -g $ppa_auto_debug
#ppa_sleep  2
