#!/bin/sh 
#load global env 

. ../../cfg/cpe_env_global
. ../../cfg/ppa_auto_env
. ../../cfg/ppa_auto_testcase_env

#load local env
. cpe/cpe_env
. wan/wan_env
. lan/lan_env


set_ip_address "$ppa_auto_if_cpe.$lan_vlan_id" "$lan_ip" "$ipv6_subnetmask"
set_routeing_table_lanside "$cpe_wan_gw_6rd_ipv6" "$cpe_lan_ip" "128" "$ppa_auto_if_cpe.$lan_vlan_id" 

