#!/bin/sh 
#load global env 

. ../../cfg/cpe_env_global
. ../../cfg/ppa_auto_env
. ../../cfg/ppa_auto_testcase_env

#load local env
. cpe/cpe_env
. wan/wan_env
. lan/lan_env

sec=20
#Comment out below four lines to prevent ppa_defunct in WAN PC
#cmd="killall iperf 2>&1 > /dev/null"
#$ppa_auto_tool -i $ppa_auto_if_wan -n $ppa_auto_name -t wan -c cmd -s "$cmd" -r 0
#cmd="/usr/bin/iperf -o /dev/null/ -s &"
#$ppa_auto_tool -i $ppa_auto_if_wan -n $ppa_auto_name -t wan -c cmd -s "$cmd" -r 0
iperf -c "$cpe_wan_gw" -i 1 -t $sec >  $ppa_auto_testcase_log_folder/result
#cat $ppa_auto_testcase_log_folder/result | grep sec | head -$sec | tail -1 | tr - " " | awk '{print $4,$8,$9}' > $ppa_auto_packet_result_file
cat $ppa_auto_testcase_log_folder/result | awk 'END{print}' | tr - " " | awk '{print $4,$8,$9}' > $ppa_auto_packet_result_file

