#!/bin/sh 
#load global env 

. ../../cfg/cpe_env_global
. ../../cfg/ppa_auto_env
. ../../cfg/ppa_auto_testcase_env

#load local env
. cpe/cpe_env
. wan/wan_env
. lan/lan_env


set_ip_address "$ppa_auto_if_cpe.$lan_vlan1_id" "$lan_ip1"
set_ip_address "$ppa_auto_if_cpe.$lan_vlan2_id" "$lan_ip2"
set_routeing_table_lanside "$cpe_wan_subnet1" "$cpe_lan_ip1" "$cpe_wan_netmask1"
set_routeing_table_lanside "$cpe_wan_subnet2" "$cpe_lan_ip2" "$cpe_wan_netmask2"


