#!/bin/sh 
#load global env 

. ../../cfg/cpe_env_global
. ../../cfg/ppa_auto_env
. ../../cfg/ppa_auto_testcase_env

#load local env
. cpe/cpe_env
. wan/wan_env
. lan/lan_env



#get_dynamic_ppp_interfacename_and_set_route_wan_l2tp "IPV4" "$lan_ip" "32"




