#!/bin/sh

. ../../cfg/cpe_env_global
#load global env 
. ../../cfg/ppa_auto_env
. ../../cfg/ppa_auto_testcase_env

#load local env
. cpe/cpe_env
. lan/lan_env
. wan/wan_env

../../bin/Wan_Reset_Script.sh
get_wanserver_if_via_cpe_wanif $cpe_wan_if $fixed_wan_side_if
cmd="$wan_ppa_bin_path/mc_trigger.sh $wan_ppa_bin_path $ppa_auto_name $tmp_wanserver_if $multicast_ip $multicast_ip_num &"
${ppa_auto_tool_path} -i $ppa_auto_if_wan -n $ppa_auto_name -t wan -c cmd -s "$cmd"

wan/wan_init

