#!/bin/sh 

. /var/cpe_env_global
#bridge with single wan itnerface and single outvlan. LAN no vlan
#br0: $cpe_lan_if $phy_wan_ifname0
. /var/ppa_auto_env
. /var/cpe_env

if [ $cpe_nat_enable -gt 0 ]; then 
    iptables -t nat -A POSTROUTING -o $cpe_wan_if -j MASQUERADE
fi

echo 1 > /proc/sys/net/ipv4/ip_forward
echo 1 > /proc/sys/net/ipv6/conf/all/forwarding
echo 1 > /proc/sys/net/netfilter/nf_conntrack_tcp_be_liberal  

echo "set_ip_address $cpe_wan_if $cpe_wan_ip $ipv6_subnetmask"
set_ip_address "$cpe_wan_if" "$cpe_wan_ip" "$ipv6_subnetmask"
gre="gre${ppa_auto_name}"
echo "ip -6 link add $gre type ip6gretap remote $cpe_wan_gw local $cpe_wan_ip ttl 255"
ip -6 link add $gre type ip6gretap remote $cpe_wan_gw local $cpe_wan_ip ttl 255
echo "ip -6 link set $gre up"
ip -6 link set $gre up
brctl addif br0 $gre



