#!/bin/sh 
#load global env 

. ../../cfg/cpe_env_global
. ../../cfg/ppa_auto_env
. ../../cfg/ppa_auto_testcase_env

#load local env
. cpe/cpe_env
. wan/wan_env
. lan/lan_env

sec=20
echo "iperf -c "$cpe_wan_gw" -i 1 -t $sec >  $ppa_auto_testcase_log_folder/result"
iperf -c "$cpe_wan_gw" -i 1 -t $sec >  $ppa_auto_testcase_log_folder/result
#cat $ppa_auto_testcase_log_folder/result | grep sec | head -$sec | tail -1 | tr - " " | awk '{print $4,$8,$9}' > $ppa_auto_packet_result_file
cat $ppa_auto_testcase_log_folder/result | awk 'END{print}' | tr - " " | awk '{print $4,$8,$9}' > $ppa_auto_packet_result_file
